### ISSUE TITLE
Can't install on Debian bookworm with python 3.

### ISSUE THREAD

**Issue by michela** [kennethreitz/responder#518]

**Comment by michela** [comment]
```

  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/httptools
      copying httptools/_version.py -> build/lib.linux-x86_64-cpython-311/httptools
      copying httptools/__init__.py -> build/lib.linux-x86_64-cpython-311/httptools
      creating build/lib.linux-x86_64-cpython-311/httptools/parser
      copying httptools/parser/errors.py -> build/lib.linux-x86_64-cpython-311/httptools/parser
      copying httptools/parser/__init__.py -> build/lib.linux-x86_64-cpython-311/httptools/parser
      running egg_info
      writing httptools.egg-info/PKG-INFO
      writing dependency_links to httptools.egg-info/dependency_links.txt
      writing requirements to httptools.egg-info/requires.txt
      writing top-level names to httptools.egg-info/top_level.txt
      reading manifest file 'httptools.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info/SOURCES.txt'
      copying httptools/parser/parser.c -> build/lib.linux-x86_64-cpython-311/httptools/parser
      warning: build_py: byte-compiling is disabled, skipping.

      running build_ext
      building 'httptools.parser.parser' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/httptools
      creating build/temp.linux-x86_64-cpython-311/httptools/parser
      creating build/temp.linux-x86_64-cpython-311/vendor
      creating build/temp.linux-x86_64-cpython-311/vendor/http-parser
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g
-fwrapv -O2 -fPIC -I/home/princess/.local/share/virtualenvs/grapho-server-ZnSZrAOm/include -I/usr/include/python3.11
-I/tmp/pip-install-rztb6o0p/httptools_a44308e2f9824e2e942a95b1cf098c6c/vendor/http-parser -c httptools/parser/parser.c -o
build/temp.linux-x86_64-cpython-311/httptools/parser/parser.o -O2
      httptools/parser/parser.c:212:12: fatal error: longintrepr.h: No such file or directory
        212 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1


  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for httptools
  error: subprocess-exited-with-error

  × Running setup.py install for httptools did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running install
      /home/princess/.local/share/virtualenvs/grapho-server-ZnSZrAOm/lib/python3.11/site-packages/setuptools/command/install.py:34:
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/httptools
      copying httptools/_version.py -> build/lib.linux-x86_64-cpython-311/httptools
      copying httptools/__init__.py -> build/lib.linux-x86_64-cpython-311/httptools
      creating build/lib.linux-x86_64-cpython-311/httptools/parser
      copying httptools/parser/errors.py -> build/lib.linux-x86_64-cpython-311/httptools/parser
      copying httptools/parser/__init__.py -> build/lib.linux-x86_64-cpython-311/httptools/parser
      running egg_info
      writing httptools.egg-info/PKG-INFO
      writing dependency_links to httptools.egg-info/dependency_links.txt
      writing requirements to httptools.egg-info/requires.txt
      writing top-level names to httptools.egg-info/top_level.txt
      reading manifest file 'httptools.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info/SOURCES.txt'
      copying httptools/parser/parser.c -> build/lib.linux-x86_64-cpython-311/httptools/parser
      warning: build_py: byte-compiling is disabled, skipping.

      running build_ext
      building 'httptools.parser.parser' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/httptools
      creating build/temp.linux-x86_64-cpython-311/httptools/parser
      creating build/temp.linux-x86_64-cpython-311/vendor
      creating build/temp.linux-x86_64-cpython-311/vendor/http-parser
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g
-fwrapv -O2 -fPIC -I/home/princess/.local/share/virtualenvs/grapho-server-ZnSZrAOm/include -I/usr/include/python3.11
-I/tmp/pip-install-rztb6o0p/httptools_a44308e2f9824e2e942a95b1cf098c6c/vendor/http-parser -c httptools/parser/parser.c -o
build/temp.linux-x86_64-cpython-311/httptools/parser/parser.o -O2
      httptools/parser/parser.c:212:12: fatal error: longintrepr.h: No such file or directory
        212 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

**Comment by michela** [comment]
I've been able to build with tihs workaround

```
cython = "==3.0.10"
httptools = "==0.6.1"
responder = {editable = true, ref = "e9613500daf2432af5efd4910168112675004d22", git = "git+https://github.com/taoufik07/responder.git"}
```

**Comment by amotl** [comment]
Hi @michela,

apologies for the very late reply. We just released v3.0.0.dev0. Can we humbly ask you to test if this improves the situation for you?

- GH-578

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi. Using this command, as demonstrated in GH-578, it looks like the new package will work on Python 3.8 through Python 3.13.
```shell
uv run --with='responder[cli]>=3.0.0.dev0' -- responder --version
```
