### ISSUE TITLE
[2025] Releasing version 3.0.0

### ISSUE THREAD

**Issue by amotl** [kennethreitz/responder#578]
## About
We are intending to release Responder 3.0.0.

## Notes
- responder 3.0.0 is largely compatible with responder 2.0.0,
  and unlocks using it with Python 3.11 and higher.
- All subsystems have been refactored to be true extensions,
  see `responder.ext.{cli,graphql,openapi,schema}`.

## Preview
Pre-release packages are available on PyPI. Feedback is very much welcome.
- **PyPI:** [responder==3.0.0.dev0](https://pypi.org/project/responder/3.0.0.dev0/)
- **Documentation:** https://responder.readthedocs.io/
- **Installation:**
  ```
  uv pip install --upgrade 'responder>=3.0.0.dev0'
  ```

## Demo
Demonstrate package downloading and invocation works well.
```
uvx --with='responder[cli]>=3.0.0.dev0' responder --version
```
<details>
<summary>variants</summary>

#### uv solo
```shell
uv run --with='responder[cli]>=3.0.0.dev0' -- responder --version
uv run --python=3.8 --with='responder[cli]>=3.0.0.dev0' -- sh -c "python -V; responder --version"
uv run --python=3.13 --with='responder[cli]>=3.0.0.dev0' -- sh -c "python -V; responder --version"
```
#### uv+Docker
```shell
export PYTHON=python3.8
export PYTHON=python3.13
docker run "ghcr.io/astral-sh/uv:${PYTHON}-bookworm-slim" \
  uv run --with='responder[cli]>=3.0.0.dev0' -- responder --version
```
</details>

## Downstream
Updates to responder 3.0.0, validated on downstream projects.
- https://github.com/daq-tools/vasuki/pull/28

## Details

<details>
<summary>What's inside</summary>

### Maintenance
Currently, the package can't be installed on current systems, i.e. Python 3.11+.
The next release intends to improve this situation.
- GH-470
- GH-496
- GH-518
- GH-522
- GH-525

### Code wrangling
Some subsystem modules got lost on the `main` branch.
Those patches bring them back into `responder.ext`.

- GH-547
  - GH-549
  - GH-576
- GH-551
  - GH-554
- Feature: Bring back OpenAPI extension
  - GH-555

### Documentation
The documentation is on RTD now.
- GH-564
  - https://responder.readthedocs.io/

</details>

**Comment by adrian-kuhn** [comment]
Hi Andreas,
that's good news! I'm happy to test it with our next release and let you now, if we encounter any problems.

Thank you for your great work with this great library,
Adrian

**Comment by amotl** [comment]
Hi again. I am hereby pinging all 77 contributors, to check out the new pre-release, probing the chance that they might still be using the package in one way or another.

```
http "https://api.github.com/repos/kennethreitz/responder/contributors?per_page=100" | \
  jq -r '["@" + .[].login] | sort | @csv' | tr -d '"' | sed 's/,/, /g'
```

/cc @0x49D1, @0xflotus, @BNMetrics, @CianciuStyles, @EdwardBetts, @FirstKlaas, @Hwesta, @JayjeetAtGithub, @MRSharff, @MerleLiuKun, @MichaelPereira, @Nitish18, @ParthS007, @StevenAvelino24, @TomFaulkner, @aaqaishtyaq, @aitoehigie, @amikrop, @amotl, @artemgordinskiy, @barrust, @carlodri, @cdfuller, @condemil, @daikeren, @daphil19, @dependabot[bot], @ewjoachim, @frostming, @gdamjan, @goodbadwolf, @ibnesayeed, @javad94, @jeremiahpslewis, @jonbeebe, @jordaneremieff, @josegonzalez, @kennethreitz, @kobayashi, @majiang, @mathiasose, @metakermit, @mlschneid, @mmanhertz, @mtcronin99, @nicksspirit, @nicoddemus, @parberge, @pbsds, @pesap, @pyasi, @rcatajar, @repodevs, @rparrapy, @rpost, @ryuuji, @serhii73, @sheb, @shyamjos, @sloria, @squiddy, @steinnes, @tabotkevin, @taoufik07, @tedder, @timgates42, @timofurrer, @tkamenoko, @tomchristie, @tselepakis, @ucpr, @valtyr, @vbarbaresi, @vlcinsky, @vuonghv, @waghanza, @xyb

**Comment by amotl** [comment]
Splitted into a second post, because GitHub apparently has a limit on the maximum number of referenced user handles.

/cc @pyasi, @rcatajar, @repodevs, @rparrapy, @rpost, @ryuuji, @serhii73, @sheb, @shyamjos, @sloria, @squiddy, @steinnes, @tabotkevin, @taoufik07, @tedder, @timgates42, @timofurrer, @tkamenoko, @tomchristie, @tselepakis, @ucpr, @valtyr, @vbarbaresi, @vlcinsky, @vuonghv, @waghanza, @xyb

**Comment by waghanza** [comment]
responder has been removed from https://web-frameworks-benchmark.netlify.app/result?l=python, since https://github.com/the-benchmarker/web-frameworks/pull/5769#issuecomment-1296247886

I can re-introduce it if you like ❤

**Comment by waghanza** [comment]
can you give me a simple code that implements 3 endpoints : GET /, POST /user/ and GET /user/:id ? and obviously make me a recommendation for engine to use in a production environment (uvicorn, gunicorn, daphne, hypercorn ...) @amotl ?

**Comment by amotl** [comment]
Hi @waghanza, we are just leaving for a week of vacation, so I am sorry I can't provide any more details right now. Responder uses uvicorn, if that answers your second question?

**Comment by waghanza** [comment]
I can not install this beta. I have
```python
pip install .root@8d1c5695aad9:/usr/src/app# pip install .
Processing /usr/src/app
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-wu2i3oks/overlay/lib/python3.13/site-packages/flit_core/buildapi.py", line 31, in get_requires_for_build_wheel
          module = Module(info.module, Path.cwd())
        File "/tmp/pip-build-env-wu2i3oks/overlay/lib/python3.13/site-packages/flit_core/common.py", line 59, in __init__
          raise ValueError("No file/folder found for module {}".format(name))
      ValueError: No file/folder found for module server
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

my pyproject is
```toml
[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core"]

[project]
name='server'
version = '1.0.0'
description = "Simple benchmark implementation"
dependencies = ["responder==3.0.0.dev0"]
```

**Comment by nicksspirit** [comment]
@waghanza why don't you try installing with uv instead.

**Comment by waghanza** [comment]
Since we use flirt to install dependencies on all our framework @nicksspirit. The initial idea was to use pyproject, and flirt seems accurate for this simple task

Any suggestion?

**Comment by nicksspirit** [comment]
Sure, just offering a troubleshooting solution. @amotl used uv to install,
why don't you try that to rule out if the issue is how the responder
package is configured. Then you can dig deeper into your pyproject.toml.

**Comment by waghanza** [comment]
I tried and
```python
root@dec4b844477f:/usr/src/app# uv pip install responder --system
Using Python 3.13.1 environment at: /usr/local
Resolved 39 packages in 1.92s
   Built docopt==0.6.2
   Built promise==2.3
   Built graphql-server-core==2.0.0                                                                                                                                                                                x Failed to build `httptools==0.1.2`
  |-> The build backend returned an error
  `-> Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stdout]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-aarch64-cpython-313/httptools
      copying httptools/__init__.py -> build/lib.linux-aarch64-cpython-313/httptools
      copying httptools/_version.py -> build/lib.linux-aarch64-cpython-313/httptools
      creating build/lib.linux-aarch64-cpython-313/httptools/parser
      copying httptools/parser/__init__.py -> build/lib.linux-aarch64-cpython-313/httptools/parser
      copying httptools/parser/errors.py -> build/lib.linux-aarch64-cpython-313/httptools/parser
      running egg_info
      writing httptools.egg-info/PKG-INFO
      writing dependency_links to httptools.egg-info/dependency_links.txt
      writing requirements to httptools.egg-info/requires.txt
      writing top-level names to httptools.egg-info/top_level.txt
      reading manifest file 'httptools.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info/SOURCES.txt'
      copying httptools/parser/parser.c -> build/lib.linux-aarch64-cpython-313/httptools/parser
      running build_ext
      building 'httptools.parser.parser' extension
      creating build/temp.linux-aarch64-cpython-313/httptools/parser
      creating build/temp.linux-aarch64-cpython-313/vendor/http-parser
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/root/.cache/uv/builds-v0/.tmpQSFusd/include -I/usr/local/include/python3.13
      -I/root/.cache/uv/sdists-v7/pypi/httptools/0.1.2/WU41YbJKc7if13NHGeBHy/src/vendor/http-parser -c httptools/parser/parser.c -o build/temp.linux-aarch64-cpython-313/httptools/parser/parser.o -O2                                                                                                                                                                                                                                  [stderr]
      /root/.cache/uv/builds-v0/.tmpQSFusd/lib/python3.13/site-packages/setuptools/_distutils/dist.py:270: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      httptools/parser/parser.c:212:12: fatal error: longintrepr.h: No such file or directory
        212 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1

      hint: This error likely indicates that you need to install a library that provides "longintrepr.h" for `httptools@0.1.2`
  help: `httptools` (v0.1.2) was included because `responder` (v2.0.7) depends on `uvicorn[standard]` (v0.13.2) which depends on `httptools`
```

**Comment by waghanza** [comment]
sorry, it work with ==3.0.0.dev0

**Comment by michela** [comment]
>All subsystems have been refactored to be true extensions,
see responder.ext.{cli,graphql,openapi,schema}.

Can you elaborate on what the above means?

My app is working apart from the Swagger openapi UI as below

`jinja2.exceptions.TemplateNotFound: 'swagger_ui.html' not found in search path: '/home/michela/.local/share/virtualenvs/grapho-server-jJZ_4mcz/lib/python3.12/site-packages/responder/ext/openapi/docs'`

**Comment by michela** [comment]
Also tried pulling and installing the latest main commit https://github.com/kennethreitz/responder/commit/944d47da45db16b904ced22fb731b3c3959406d6 (where I can see the openapi/docs)
 
`uv pip install ".[full]`"

but the docs folder doesn't get copied to site-packages (and manual copying there just resulted in complaints about /schema.yml not found).

**Comment by amotl** [comment]
Hi @michela. Thank you so much for reporting those flaws. 💯
In order to run a dedicated conversation about the problems you are observing, I've just created separate ticket.

- GH-583

**Comment by kennethreitz** [comment]
Responder 3.0.0 was released, now at 3.4.1. Closing.
